version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    restart: always
    environment:
      username: test
      password: test
    volumes:
      - .:/app
    working_dir: /app
    ports: 
      - "8010:8010"
    networks:
      - fiber

networks:
  fiber:

volumes:
  dbdata:
    driver: local
  redisdata1:
    driver: local
